Things I forgot to do (Cinemachine)
BonusPlay/Projekt-Kolowy-2018Z pull request #2
Opened 2018-12-02 12:04 UTC by Dirtowladny

moved test functions to another script.
created camera prefab.
assigned default values in effects.
added more comments.
camera follow script has much more functionality, can now switch targets, save player's game object for future reference, stop following target, follow saved player.
removed "not implemented yet" comments

2018-12-02 21:51 UTC, BonusPlay requested changes

2018-12-02 21:51 UTC, BonusPlay commented on Assets/Scripts/PlayerMovementController.cs
> +			if(AntiSlideStrength <= 1f){
Staraj się unikać rozdzielania logiki na pół, tam gdzie to nie jest potrzebne. `antiSlide` powinno być local variable w funkcji `AntiSlide`.

2018-12-02 21:51 UTC, BonusPlay commented on Assets/Scripts/PlayerMovementController.cs
> +				return 2f;
Warning jest OK, ale nie zakazuj ludziom robić czegoś głupiego. It's not a bug, it's a feature.

2018-12-09 10:14 UTC, Dirtowladny commented
gotowe, przy okazji dodałem już pocisk. Jako iż nie miałem wroga do testów to zrobiłem sobie dużą kostkę na środku sceny która teleportuje się do góry proporcjonalnie do otrzymanych obrażeń

2018-12-10 21:42 UTC, BonusPlay requested changes

2018-12-10 21:42 UTC, BonusPlay commented on Assets/Scripts/PlayerMovementController.cs
> +	private bool IdiotProofAntiSlide = true;
but why

2018-12-11 22:43 UTC, merged